# ==========================================
# Configuración del Servidor Web
# ==========================================
server.port=8085

# ==========================================
# Configuración Conexión MySQL (phpMyAdmin - tienda_parking)
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/tienda_parking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# Configuración de JPA / Hibernate para MySQL
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# Configuración de Thymeleaf Templates
# ==========================================
spring.thymeleaf.cache=false
